application: rich-brace-854
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /admin
  script: src.consider.application
  login: admin
  auth_fail_action: redirect

- url: /toggleInstructor
  script: src.consider.application
  login: admin

- url: /.*
  script: src.consider.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest