application: rich-brace-854
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /secretlandingpage
  script: manadmin.application

- url: /.*
  script: consider.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest